# You can use this as an alternate gatekeeper
#
#    gatekeeper:
#        image: "deciphernow/gm-proxy:latest"
#        volumes:
#            - ./:/opt
#        ports:
#            - 8080:7979  # 7979 is our tls listener
#

[global]
zk_addrs = ["zk:2181"]
httpsPort = "8080"
cert = "/opt/server.cert.pem"
key = "/opt/server.key.pem"
trust = "/opt/server.trust.pem"

[[upstream]]
proxy_prefix = "/services/object-drive/1.0"
name = "object-drive"
version = "1.0"
sd = "zk"
path = "/services/object-drive/1.0/https"
port_path = "serviceEndpoint.port"
host_path = "serviceEndpoint.host"
tls = true

