

database:
    driver: "mysql"
    username: ""
    password: ""
    protocol: ""
    host: ""
    port: "9999"
    schema: ""
    params: ""
    use_tls: true
    insecure_skip_verify: false
    trust: ""
    cert: ""
    key: ""
    deadlock_retrycounter: 30
    deadlock_retrydelay: 55
    max_idle_conns: 10
    max_open_conns: 10
    max_conn_lifetime: 30

server:
    base_path: "blah/blah"
    port: ""
    bind: ""
    use_tls: true
    trust: ""
    cert: ""
    key: ""
    masterkey: ""
    ciphers:
        - "foo"
        - "baz"
    min_version: ""
    acl_whitelist:
        - "foo"
        - "baz"
    static_root: ""
    template_root: ""
    timeout_idle: 60
    timeout_read: 0
    timeout_readheader: 5
    timeout_write: 3600


disk_cache:
    root_dir: ""
    partitiion: ""
    low_threshold_percent: 40
    high_threshold_percent: 90
    evict_age: 0
    walk_sleep: 0
    chunk_size:
    masterkey: ""

aac:
    trust: "foo"
    cert: ""
    key: ""
    healthcheck: "{\"version\":\"2.1.0\",\"classif\":\"U\"}"
    hostname: ""
    port: ""
    zk_path: ""
    warmup_time: 5
    recheck_time: 30

event_queue:
    kafka_addrs:
        - ""
    zk_addrs:
        - "foo"
        - "baz"
    publish_failure_actions:
        - "*"
    publish_success_actions:
        - "access"
        - "authenticate"
        - "create"
        - "delete"
        - "list"
        - "undelete"
        - "unknown"
        - "update"
        - "zip"
    topic: "odrive-event"

zk:
    ip: ""
    port: ""
    address: ""
    register_odrive_as: ""
    retrydelay: 10
    recheck_time: 30
