

database:
    driver: "mysql"
    username: ""
    password: ""
    protocol: ""
    host: ""
    port: "9999"
    schema: ""
    params: ""
    use_tls: true
    insecure_skip_verify: true
    trust: ""
    cert: ""
    key: ""

server:
    base_path: "blah/blah"
    port: ""
    bind: ""
    use_tls: true
    trust: ""
    cert: ""
    key: ""
    masterkey: ""
    ciphers:
        - "foo"
        - "baz"
    min_version: ""
    acl_whitelist:
        - "foo"
        - "baz"
    static_root: ""
    template_root: ""


disk_cache:
    root_dir: ""
    partitiion: ""
    low_watermark: 0
    high_watermark: 0
    evict_age: 0
    walk_sleep: 0

aac:
    trust: "foo"
    cert: ""
    key: ""
    hostname: ""
    port: ""
    zk_path: ""

event_queue:
    kafka_addrs:
        - ""
    zk_addrs:
        - "foo"
        - "baz"
    publish_failure_actions:
        - "*"
    publish_success_actions:
        - "access"
        - "authenticate"
        - "create"
        - "delete"
        - "list"
        - "undelete"
        - "unknown"
        - "update"
        - "zip"

zk:
    ip: ""
    port: ""
    address: ""
    register_odrive_as: ""
