#!/bin/bash

# This script is deprecated. To only run the aac container, run the following from /object-drive/docker
# 
# docker-compose up -d aac

echo "WARNING: This script is deprecated."

docker run -u root --add-host zk1:192.168.99.102 --add-host zk2:192.168.99.102 --add-host zk3:192.168.99.102 -p 2181:2181 -p 9093:9093 -d aac:latest /root/entry

