image: docker.363-283.io/docker/backend:maven-3.3.9-jdk-8

stages:
  - publish
        
docker-publish-job:
    stage: publish

    script:
        # Sync from docker hub, re-tag, push to gitlab registry
        - service docker start; sleep 2;
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - docker pull deciphernow/odrive
        - docker pull deciphernow/metadatadb
        - docker tag deciphernow/odrive docker.363-283.io/cte/object-drive-server 
        - docker tag deciphernow/metadatadb docker.363-283.io/cte/object-drive-server:metadatadb
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN docker.363-283.io
        - docker push docker.363-283.io/cte/object-drive-server 
        - docker push docker.363-283.io/cte/object-drive-server:metadatadb

    only:
        - develop       

