#!/bin/bash

cd `dirname ${0}`
odriverpmbuilt=`docker images | grep odriverpm-bc -c`

if [ "${odriverpmbuilt}" == "1" ]
then
  echo "docker image deciphernow/odriverpm-bc already built"
else
  echo "docker image deciphernow/odriverpm-bc needs to be built"
  ./scripts/makeimage
fi

ARG_VERSION=${1}
if [ ${#1} -eq 0 ]
then
  ARG_VERSION=$(grep -m 1 '## Release' changelog.md|awk '{print $3}')b4
  echo Version was not specified. Using $ARG_VERSION
fi

ARG_BUILDNUM=${2}
if [ ${#2} -eq 0 ]
then  
  ARG_BUILDNUM=$(cat BUILDNUMBER) 
  if [ -z ${CIRCLE_BUILD_NUM} ]; then
    echo Build Number was not specified. Using $ARG_BUILDNUM
  fi
fi

if [ -z ${CIRCLE_BUILD_NUM} ]; then
  CIRCLE_BUILD_NUM=$ARG_BUILDNUM
fi

( ./makedocs ${ARG_VERSION} ${ARG_BUILDNUM} )
docker run --rm -i \
   -e ODRIVE_PACKAGE_NAME="odrive-${ARG_VERSION}" \
   -e ODRIVE_VERSION=${ARG_VERSION} \
   -e CIRCLE_BUILD_NUM=${CIRCLE_BUILD_NUM} \
   -e CIRCLE_SHA1=${CIRCLE_SHA1} \
   -e TAG_VERSION=${3} \
   -v `pwd`:/go/src/bitbucket.di2e.net/dime/object-drive-server deciphernow/odriverpm-bc:latest scripts/build.sh


