#!/bin/bash

cd `dirname $0`

TEMPLATES=server/static/templates

#Use humangeo's aglio container and copy artifact to where it needs to be
docker run -ti -v `pwd`:/docs humangeo/aglio -i docs/home.md --theme-variables streak -o api.html
mkdir -p server/static/templates
mv -f api.html ${TEMPLATES}/api.html

docker run -ti -v `pwd`:/docs humangeo/aglio -i changelog.md --theme-variables streak -o changelog.html
mv -f changelog.html ${TEMPLATES}/changelog.html

docker run -ti -v `pwd`:/docs humangeo/aglio -i docs/overview.md --theme-variables streak -o overview.html
mv -f overview.html ${TEMPLATES}/root.html

# Hack to view root locally.
cp ${TEMPLATES}/root.html server

(cd docs && ./builddiagrams)
