#!/bin/bash

cd `dirname $0`

#Use humangeo's aglio container and copy artifact to where it needs to be
docker run --rm -ti -v `pwd`:/docs humangeo/aglio -i docs/home.md --theme-variables streak -o root.html
mv root.html cmd/odrive/libs/server/static/templates/root.html


