#!/bin/bash

# This script should be run whenever we have a drive ui release intended to be
# pushed to the MEME Dev VPC for Bedrock
#
# Publishes the Drive UI RPM to the buids.363-283.io S3 bucket for Bedrock. The
# Drive UI RPM is custom for bedrock, and is built on demand, using the gitlab 
# pipeline number as the version for the RPM. RPM filenames are converted to a 
# format that denotes the version and build date. Prior to uploading to S3 
# bucket, you will be prompted for each, allowing opportunity to test builds, 
# and exit to verify structure.
#
# Pre-requisites
#   1. You have the gitlab cte/object-drive-ui project cloned to 
#      $OD_ROOT/object-drive-ui on develop branch
#   2. You have environment variables set for MEME_AWS_ACCESS_KEY_ID and 
#      MEME_AWS_SECRET_ACCESS_KEY for writing to the builds.363-283.io bucket
#   3. You have environment varaibles set for GITLAB_TOKEN to access the API 
#      from Gitlab to read and determine pipeline version number

COUNTMEMEAWSKEY=$(printenv | grep "MEME_AWS_ACCESS_KEY_ID" -c)
if [ $COUNTMEMEAWSKEY -eq 0 ]
then
  echo "envvar MEME_AWS_ACCESS_KEY_ID is not set"
  exit 1
fi
COUNTMEMESECRET=$(printenv | grep "MEME_AWS_SECRET_ACCESS_KEY" -c)
if [ $COUNTMEMESECRET -eq 0 ]
then
  echo "envvar MEME_AWS_SECRET_ACCESS_KEY is not set"
  exit 1
fi
if [ ! "$GITLAB_TOKEN" ]
then
  echo "envvar GITLAB_TOKEN is not set"
  exit 1
fi

export AWS_ACCESS_KEY_ID=$MEME_AWS_ACCESS_KEY_ID
export AWS_SECRET_ACCESS_KEY=$MEME_AWS_SECRET_ACCESS_KEY

# Determine what the version will be (from UI package.json)
DRIVE_UI_VERSION="$(grep '"version":' ${OD_ROOT}/object-drive-ui/package.json|sed 's/\"version\": \"//g'|sed 's/\",//g'|sed 's/ //g'|sed 's/-/./g')"
# Determine What the release will be (from UI Pipeline)
DRIVE_UI_PIPELINE="$(curl -s --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}" "https://gitlab.363-283.io/api/v3/projects/639/pipelines" | grep -Po '"id":.*?[^\\]",' | head -1 | sed -e 's/,.*//' | sed -e 's/"id"://')"

# Build the UI (resulting RPM is drive-1.0-{pipeline#}.x86_64.rpm)
BUILDDATEUI=$(date +%Y%m%d)
UIRPMFILE="drive-1.0-bedrock.x86_64.rpm"
cd ${OD_ROOT}/object-drive-ui
jspm install
npm run build
./buildimage.sh
cd ${OD_ROOT}/object-drive-ui/rpm
./build-bedrock

# File format needs to be
# <App Name>-<major version>.<minor version>.<patch version>.<build number>.<YYYYMMDD>.{SNAPSHOT}.rpm
# drive-ui-1.0.0.{CIRCLE_BUILD_NUM}.{BUILDDATEUI}.SNAPSHOT.rpm
UIREMOTEFILE="drive-ui-${DRIVE_UI_VERSION}.${DRIVE_UI_PIPELINE}.${BUILDDATEUI}.SNAPSHOT.rpm"
echo "File to save as in bucket is ${UIREMOTEFILE}"
echo "Command: aws s3 cp ${UIRPMFILE} s3://builds.363-283.io/${UIREMOTEFILE}"
echo "Do you wish to copy to the builds.363-283.io bucket?"
select yn in "Yes" "No"; do
  case $yn in
    "Yes") 
      aws s3 cp ${UIRPMFILE} s3://builds.363-283.io/${UIREMOTEFILE}
      break
      ;;
    "No") 
      break
      ;;
  esac
done

