#!/bin/bash

set -euo pipefail

export CA='../../defaultcerts/clients/client.trust.pem'
export CERT='../../defaultcerts/clients/test_0.cert.pem'
export KEY='../../defaultcerts/clients/test_0.key.pem'

export UDN='cn=test tester10,ou=people,ou=dae,ou=chimera,o=u.s. government,c=us'
export SDN="cn=twl-server-generic2,ou=dae,ou=dia,ou=twl-server-generic2,o=u.s. government,c=us"

#curl --header "USER_DN: ${UDN}" --header "EXTERNAL_SYS_DN: ${SDN}" --header "SSL_CLIENT_S_DN: ${SDN}" --form 'ObjectMetadata={"typeName":"File","name":"TEST-acmwithdeclass-2019-01-28","acm":{"classif":"TS","classif_rsn":"eo","classif_dt":"2019-01-28","classif_by":"me","declass_dt":"2040-12-31","version":"2.1.0"}}' --form 'blob=@"curlupload"' --insecure --cacert ${CA} --cert ${CERT} --key ${KEY} https://meme.363-283.io/services/object-drive/1.0/objects >> /dev/null

curl --form 'ObjectMetadata={"typeName":"File","name":"TEST-acmwithdeclass-2019-01-28","containsUSPersonsData":"Yes","exemptFromFOIA":"Yes","properties":[{"name":"myproperty","value":"thevalue","classificationPM":"what"}],"acm":{"classif":"TS","classif_rsn":"eo","complies_with":"alphabet-soup","classif_dt":"2019-01-28","classif_by":"me","poc":"someone","deriv_from":"xyz","declass_event":"fire","version":"2.1.0"}}' --form 'blob=@"curlupload"' --insecure --cacert ${CA} --cert ${CERT} --key ${KEY} https://meme.363-283.io/services/object-drive/1.0/objects >> /dev/null



# classif_rsn
# classif_by
# complies_with
# classif_dt
# declass_dt
# declass_event
# declass_ex
# deriv_class_by
# deriv_from
# des_version
# notice_rsn
# poc
# rsrc_elem
# compil_rsn
# ex_from_rollup
