#!/bin/bash

set -euo pipefail

export CA='../../defaultcerts/clients/client.trust.pem'
export CERT='../../defaultcerts/clients/test_0.cert.pem'
export KEY='../../defaultcerts/clients/test_0.key.pem'

export UDN='cn=test tester10,ou=people,ou=dae,ou=chimera,o=u.s. government,c=us'
export SDN="cn=twl-server-generic2,ou=dae,ou=dia,ou=twl-server-generic2,o=u.s. government,c=us"

COUNTER=0
DTFMT="20180516"
while true; do
  let COUNTER=COUNTER+1 
  DTFMT=$(date '+%Y/%m/%d/%H/%M')
  curl --silent --header "USER_DN: ${UDN}" --header "EXTERNAL_SYS_DN: ${SDN}" --header "SSL_CLIENT_S_DN: ${SDN}" --form 'ObjectMetadata={"typeName":"File","name":"DISP-'${DTFMT}'/'${COUNTER}'","namePathDelimiter":"/","acm":{"classif":"U","version":"2.1.0"}}' --form 'blob=@"curlupload"' --insecure --cacert ${CA} --cert ${CERT} --key ${KEY} https://localhost:4430/services/object-drive/1.0/objects >> /dev/null
done

