#!/bin/bash

docker login -u $DOCKER_USER -p $DOCKER_PASS
docker login -u $DOCKER_USER_363 -p $DOCKER_PASS_363 docker.363-283.io
docker pull deciphernow/aglio:2.3.0
docker pull deciphernow/dias:1.1.0
cd $GOPATH/src/$IMPORT_PATH/.ci && docker-compose pull zk kafka aac proxier redis


