#!/bin/bash


thisbranch=`git rev-parse --abbrev-ref HEAD`
if [ $thisbranch = $DEPLOY_BRANCH ] 
then
  # There will be one rpm in here from the build
  for r in `ls /home/circleci/rpmbuild/RPMS/x86_64/*.rpm`
  do
    r2=object-drive-${ODRIVE_VERSION}.${CIRCLE_BUILD_NUM}.x86_64.rpm
    mv $r $r2
    s3=s3://odrive-builds/circle/rpms/develop/$(date +%Y%m)/object-drive-${ODRIVE_VERSION}.${CIRCLE_BUILD_NUM}.x86_64.rpm
    echo aws s3 cp $r2 $s3 --acl private
    aws s3 cp $r2 $s3 --acl private
    echo docker push odrive and metadatadb
    docker push deciphernow/odrive:latest
    docker push deciphernow/metadatadb:latest
  done
else
  echo Merge this into $DEPLOY_BRANCH to deploy
fi


