#!/bin/bash

docker-compose stop && docker-compose rm -f && (cd gatekeeper; ./makeimage) && (cd odrive; ./makeimage) && (cd packaging; ./makeimage)
docker-compose up -d
docker-compose stop packaging
docker-compose logs -f odrive

