version: '2'

services:

  finder:  
    image: docker.363-283.io/bedrock/finder-service:1.0.0-SNAPSHOT
    # This should be the image, but getting errors on startup
    #image: docker-dime.di2e.net/dime/finder-service:1.0
    ports:
      - "16123:8443"
    depends_on:
      - zk
      - aac
      - es
      - odrive

  aac:
    image: docker-dime.di2e.net/dime/aac-service:1.2.3
    tty: true
    stdin_open: true
    ports:
      - "9093:9000"
      - "7444:7444"
    environment:
        - COM_DECIPHERNOW_SERVER_CONFIG_ZK_ZOOKEEPERCONNECTION=zk:2181
        - COM_DECIPHERNOW_SERVER_CONFIG_ZK_ANNOUNCEMENTPOINT=/cte/service/aac/1.2
        - COM_DECIPHERNOW_SERVER_CONFIG_TLS_TRUSTSTORE=/opt/config/certificates/jks/truststore.jks
        - COM_DECIPHERNOW_SERVER_CONFIG_TLS_KEYSTORE=/opt/config/certificates/jks/twlserver.jks
        - COM_DECIPHERNOW_SERVER_CONFIG_THRIFT_PORT=9000
        - COM_DECIPHERNOW_SERVER_CONFIG_REDIS_FAIL_SLEEPMILLISECONDS=3000
        - COM_DECIPHERNOW_SERVER_CONFIG_REDIS_FAIL_LOGRETRYCOUNT=60
        - GOV_IC_CTE_AAC_CONFIG_REDIS_FAIL_SLEEPMILLISECONDS=1000
        - GOV_IC_CTE_AAC_CONFIG_REDIS_FAIL_LOGRETRYCOUNT=60
        - REDIS_HOST=redis
        - ZOOKEEPER_URL=zk:2181
        - CLOUDSHARE_DIAS_ATTRIBUTE_SERVICE_ENDPOINT=https://dias/ws/services/DIASMessageReceiverService
    depends_on:
      - zk
      - redis
      - dias

  cte-user-service:
    hostname: cte-user-service
    image: docker.363-283.io/chimera/user-service:1.0.1-SNAPSHOT
    environment:
        - ELASTICSEARCH_HOST=es
        - ZK_HOST=zk
        - JAVAX_PERSISTENCE_JDBC_URL=jdbc:postgresql://postgres:5432/chimera_test
        - ZK_ANNOUNCEPOINT_AAC=/cte/service/aac/1.2
        - ZOOKEEPER_URL=zk:2181
        - GOV_IC_CTE_SERVER_CONFIG_ZK_ZOOKEEPERCONNECTION=zk:2181
    ports:
      - "7472:8443"
    depends_on:
      - zk
      - aac
      - postgres


  odrive:
    # This is the ONLY place where ":latest" should be used, and only if built locally!
    image: deciphernow/odrive-bc:latest
    # Other applications should refer to the following image!!!!
    #image: docker-dime.di2e.net/dime/object-drive-server:v1.0.18b4-bc
    mem_limit: 1024m
    cpuset: "1-3"
    environment:
        - OD_AAC_CA=/go/src/bitbucket.di2e.net/dime/object-drive-server/defaultcerts/client-aac/trust/client.trust.pem
        - OD_AAC_CERT=/go/src/bitbucket.di2e.net/dime/object-drive-server/defaultcerts/client-aac/id/client.cert.pem
        - OD_AAC_HEALTHCHECK={"version":"2.1.0","classif":"U"}
        - OD_AAC_HOST=aac                         # has default
        - OD_AAC_KEY=/go/src/bitbucket.di2e.net/dime/object-drive-server/defaultcerts/client-aac/id/client.key.pem
        - OD_AAC_CN=twl-server-generic2
        - OD_AAC_INSECURE_SKIP_VERIFY=true
        - OD_PEER_CN=twl-server-generic2
        - OD_PEER_INSECURE_SKIP_VERIFY=false
        - OD_AWS_ACCESS_KEY_ID=$OD_AWS_ACCESS_KEY_ID
        - OD_AWS_S3_ENDPOINT                    # has default
        - OD_AWS_REGION=us-east-1             # has default
        - OD_AWS_S3_BUCKET=
        - OD_AWS_SECRET_ACCESS_KEY=$OD_AWS_SECRET_ACCESS_KEY
        - OD_AWS_SECRET_KEY=$OD_AWS_SECRET_ACCESS_KEY
        - OD_CACHE_EVICTAGE                   # has default
        - OD_CACHE_HIGHWATERMARK              # has default
        - OD_CACHE_LOWWATERMARK               # has default
        - OD_CACHE_ROOT
        - OD_CACHE_WALKSLEEP
        - OD_CACHE_PARTITION
        - OD_DB_CA=/go/src/bitbucket.di2e.net/dime/object-drive-server/defaultcerts/client-mysql/trust
        - OD_DB_CERT=/go/src/bitbucket.di2e.net/dime/object-drive-server/defaultcerts/client-mysql/id/client-cert.pem
        - OD_DB_CONN_PARAMS=parseTime=true&collation=utf8_unicode_ci&readTimeout=30s
        - OD_DB_CONNMAXLIFETIME=30
        - OD_DB_HOST=metadatadb
        - OD_DB_KEY=/go/src/bitbucket.di2e.net/dime/object-drive-server/defaultcerts/client-mysql/id/client-key.pem
        - OD_DB_MAXIDLECONNS=1
        - OD_DB_MAXOPENCONNS=50
        - OD_DB_PASSWORD=dbPassword
        - OD_DB_PORT=3306
        - OD_DB_SCHEMA=metadatadb
        - OD_DB_USERNAME=dbuser
        - OD_ENCRYPT_MASTERKEY
        - OD_EVENT_KAFKA_ADDRS= #kafka:9092    # we need to scale this up, right?
        - OD_EVENT_ZK_ADDRS=zk:2181
        - OD_EVENT_PUBLISH_FAILURE_ACTIONS
        - OD_EVENT_PUBLISH_SUCCESS_ACTIONS
        - OD_EVENT_TOPIC
        - OD_LOG_LEVEL=INFO
        - OD_SERVER_ACL_WHITELIST1=cn=twl-server-generic2,ou=dae,ou=dia,ou=twl-server-generic2,o=u.s. government,c=us
        - OD_SERVER_ACL_WHITELIST2=cn=test tester10,ou=people,ou=dae,ou=chimera,o=u.s. government,c=us
        - OD_SERVER_CA=/go/src/bitbucket.di2e.net/dime/object-drive-server/defaultcerts/server/trust.pem
        - OD_SERVER_CERT=/go/src/bitbucket.di2e.net/dime/object-drive-server/defaultcerts/server/server.cert.pem
        - OD_SERVER_CIPHERS=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA
        - OD_SERVER_KEY=/go/src/bitbucket.di2e.net/dime/object-drive-server/defaultcerts/server/server.key.pem
        - OD_SERVER_PORT=4430
        - OD_SERVER_TIMEOUT_IDLE=5
        - OD_SERVER_TIMEOUT_READ=
        - OD_SERVER_TIMEOUT_READHEADER=5
        - OD_SERVER_TIMEOUT_WRITE=60
        - OD_ZK_ANNOUNCE=/cte/service/object-drive/1.0
        - OD_ZK_AAC=/cte/service/aac/1.2/thrift
        - OD_ZK_RECHECK_TIME=30
        - OD_ZK_TIMEOUT=1
        - OD_ZK_URL
    ports:
      - "4430:4430"
    depends_on:
        - metadatadb
        - aac
        - zk
        - dias
        - kafka
  
  odriverpm:
    image: deciphernow/odriverpm:latest
    mem_limit: 1024m
    cpuset: "1-3"
    environment:
        - OD_AAC_CA=/go/src/bitbucket.di2e.net/dime/object-drive-server/defaultcerts/client-aac/trust/client.trust.pem
        - OD_AAC_CERT=/go/src/bitbucket.di2e.net/dime/object-drive-server/defaultcerts/client-aac/id/client.cert.pem
        - OD_AAC_HEALTHCHECK={"version":"2.1.0","classif":"U"}
        - OD_AAC_HOST=aac                         # has default
        - OD_AAC_KEY=/go/src/bitbucket.di2e.net/dime/object-drive-server/defaultcerts/client-aac/id/client.key.pem
        - OD_AAC_CN=twl-server-generic2
        - OD_AAC_INSECURE_SKIP_VERIFY=true
        - OD_PEER_CN=twl-server-generic2
        - OD_PEER_INSECURE_SKIP_VERIFY=false
        - OD_AWS_ACCESS_KEY_ID=$OD_AWS_ACCESS_KEY_ID
        - OD_AWS_ENDPOINT                    # has default
        - OD_AWS_REGION=us-east-1             # has default
        - OD_AWS_S3_BUCKET=
        - OD_AWS_SECRET_ACCESS_KEY=$OD_AWS_SECRET_ACCESS_KEY
        - OD_AWS_SECRET_KEY=$OD_AWS_SECRET_ACCESS_KEY
        - OD_CACHE_EVICTAGE                   # has default
        - OD_CACHE_HIGHWATERMARK              # has default
        - OD_CACHE_LOWWATERMARK               # has default
        - OD_CACHE_ROOT
        - OD_CACHE_WALKSLEEP
        - OD_CACHE_PARTITION
        - OD_DB_CA=/go/src/bitbucket.di2e.net/dime/object-drive-server/defaultcerts/client-mysql/trust
        - OD_DB_CERT=/go/src/bitbucket.di2e.net/dime/object-drive-server/defaultcerts/client-mysql/id/client-cert.pem
        - OD_DB_CONN_PARAMS=parseTime=true&collation=utf8_unicode_ci&readTimeout=30s
        - OD_DB_CONNMAXLIFETIME=30
        - OD_DB_HOST=metadatadb
        - OD_DB_KEY=/go/src/bitbucket.di2e.net/dime/object-drive-server/defaultcerts/client-mysql/id/client-key.pem
        - OD_DB_MAXIDLECONNS=1
        - OD_DB_MAXOPENCONNS=50
        - OD_DB_PASSWORD=dbPassword
        - OD_DB_PORT=3306
        - OD_DB_SCHEMA=metadatadb
        - OD_DB_USERNAME=dbuser
        - OD_ENCRYPT_MASTERKEY
        - OD_EVENT_KAFKA_ADDRS= #kafka:9092    # we need to scale this up, right?
        - OD_EVENT_ZK_ADDRS=zk:2181
        - OD_EVENT_PUBLISH_FAILURE_ACTIONS
        - OD_EVENT_PUBLISH_SUCCESS_ACTIONS
        - OD_EVENT_TOPIC
        - OD_LOG_LEVEL=INFO
        - OD_SERVER_ACL_WHITELIST1=cn=twl-server-generic2,ou=dae,ou=dia,ou=twl-server-generic2,o=u.s. government,c=us
        - OD_SERVER_ACL_WHITELIST2=cn=test tester10,ou=people,ou=dae,ou=chimera,o=u.s. government,c=us
        - OD_SERVER_CA=/go/src/bitbucket.di2e.net/dime/object-drive-server/defaultcerts/server/trust.pem
        - OD_SERVER_CERT=/go/src/bitbucket.di2e.net/dime/object-drive-server/defaultcerts/server/server.cert.pem
        - OD_SERVER_CIPHERS=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA
        - OD_SERVER_KEY=/go/src/bitbucket.di2e.net/dime/object-drive-server/defaultcerts/server/server.key.pem
        - OD_SERVER_PORT=4430
        - OD_SERVER_TIMEOUT_IDLE=5
        - OD_SERVER_TIMEOUT_READ=
        - OD_SERVER_TIMEOUT_READHEADER=5
        - OD_SERVER_TIMEOUT_WRITE=60
        - OD_ZK_ANNOUNCE=/cte/service/object-drive/1.0
        - OD_ZK_AAC=/cte/service/aac/1.2/thrift
        - OD_ZK_RECHECK_TIME=30
        - OD_ZK_TIMEOUT=1
        - OD_ZK_URL
    ports:
      - "4432:4430"
    depends_on:
        - metadatadb
        - aac
        - zk
        - dias
        - kafka        

  metadatadb:
    image: docker-dime.di2e.net/dime/object-drive-metadatadb:v1.0.18b4
    mem_limit: 1024m
    cpuset: "0"
    environment:
      - MYSQL_CONTAINER_NAME=metadatadb
      - MYSQL_USER=dbuser
      - MYSQL_DATABASE=metadatadb
      - MYSQL_ROOT_PASSWORD=dbRootPassword
      - MYSQL_PASSWORD=dbPassword
      - OD_ENCRYPT_MASTERKEY
    ports:
      - 3306:3306
    command: "./docker-entrypoint.sh mysqld_safe"

  dias:
    image: docker-dime.di2e.net/dime/dias-simulator:1.1.0
    ports:
      - "8443:443"

  zk:
    image: docker-dime.di2e.net/backend/zookeeper:3.4.9
    ports:
      - "2181:2181"

  redis:
    image: docker-dime.di2e.net/backend/redis:3.2.2
    depends_on:
      - zk

  es:
    hostname: es
    image: docker-dime.di2e.net/backend/elasticsearch:1.7.2
    environment:
      - AAC_ZOOKEEPER_ANNOUNCEMENT_POINT=/cte/service/aac/1.2
    ports:
      - "9200:9200"
    depends_on:
      - zk
      - aac

  postgres:
    image: docker-dime.di2e.net/backend/postgres:9.4
    depends_on:
      - zk

  kafka:
    hostname: kafka
    image: wurstmeister/kafka:0.10.2.1
    environment:
      KAFKA_HEAP_OPTS: "-Xmx1G -Xms500M"
      KAFKA_ADVERTISED_HOST: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: zk
      KAFKA_CREATE_TOPICS: odrive-event:1:1
    ports:
      - "22181:2181"
      - "29092:9092"
      - "9092:9092"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock

  proxier:
    image: nginx
    environment:
       - AAC_SERVICE_HOST=aac
       - AAC_SERVICE_PORT=7444
       - FINDER_HOST=finder
       - FINDER_PORT=8443
       - CTE_APPS_SERVICE_HOST=apps
       - CTE_APPS_SERVICE_PORT=8443
       - CTE_USER_SERVICE_HOST=cte-user-service
       - CTE_USER_SERVICE_PORT=8443
       - ODRIVE_SERVICE_HOST=odrive
       - ODRIVE_SERVICE_PORT=4430
    volumes:
       - ./proxier:/tmp/docker
    ports:
       - "47080:80"
       - "8080:443"
    depends_on:
       - aac
       - finder
       - cte-user-service
       - odrive
    command: /bin/bash -c "env && envsubst '$$ODRIVE_SERVICE_HOST $$ODRIVE_SERVICE_PORT $$FINDER_EXTERNAL_IP $$FINDER_HOST $$FINDER_PORT $$AAC_SERVICE_HOST $$AAC_SERVICE_PORT $$CTE_APPS_SERVICE_HOST $$CTE_APPS_SERVICE_PORT $$CTE_USER_SERVICE_HOST $$CTE_USER_SERVICE_PORT' < /tmp/docker/odrive.nginx.conf.tpl > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  mongo:
    image: docker-dime.di2e.net/backend/mongo:3.0.9
    environment:
      MONGO_INITDB_ROOT_USERNAME: "bedrock_user"
      MONGO_INITDB_ROOT_PASSWORD: "password"
      MONGO_DBNAME: "bedrock"
      MONGO_INITDB_DBNAME: "bedrock"
      MONGO_INITDB_DATABASE: "bedrock"

  odrive-indexer:
    image: docker-dime.di2e.net/dime/object-drive-indexer-service:2.1.0-SNAPSHOT
    environment:
      DEBUG: "false"
      MONGO_COLLECT_ERRORS_ENABLED: "true"
      KAFKA_THREADS: "2"
      ES_CONTENT_FIELDS: "sanitizedTitle,content"
      ES_SOURCE_FIELDS: "parentId,breadcrumbs,isPDFAvailable,containsUSPersonsData,exemptFromFOIA,finderTitle,indexerTitle,typeName,description,deletedBy,permissions,contentSize,modifiedBy,id,contentType,isPDFAvailable,exemptFromFOIA,dataType,changeCount,permission,changeToken,containsUSPersonsData,parentId,contentHash,createdDate,createdBy,deletedDate,modifiedDate,name,typeId,ownedBy,sanitizedTitle"
      TIKA_OCR_ENABLED: "false"
      TIKA_EXTRACT_TIMEOUT_SECONDS: "120"
      TIKA_OCR_MAX_SIZE_MB: "20"
      ES_HOSTS: "es:9200"
      ES_MAPPINGS_DIR: "etc/mappings/es5"
      ES_INDEX_NAME: "odrive_v001"
      TIKA_EXTRACT_SIZE_MB: "10"
      TIKA_EXTRACT_MAX_PDF_SIZE_MB: "10"
    ports:
      - "7555:8443"
      - "4001:4001"
#    volumes: # Uncomment to update test tika config updates without rebuilding service
#      - ./docker/tika/tika-config.xml:/opt/services/odrive-indexer-2.0/etc/tika-config.xml
    depends_on:
      - es
      - kafka
      - zk
