version: '2'

services:

  finder:
    image: docker.363-283.io/bedrock/finder-service:1.0.0-SNAPSHOT
    ports:
      - "16123:8443"
    depends_on:
      - zk
      - aac
      - es
      - odrive

  aac:
    image: docker.363-283.io/cte/cte-security-service:1.1.3
    tty: true
    stdin_open: true
    ports:
      - "9093:9000"
      - "7444:8443"
    environment:
      GOV_IC_CTE_SERVER_CONFIG_ZK_ZOOKEEPERCONNECTION: zk:2181
      GOV_IC_CTE_SERVER_CONFIG_ZK_ANNOUNCEMENTPOINT: /cte/service/aac/1.1
      REDIS_HOST: redis
      ZOOKEEPER_URL: zk:2181
      CLOUDSHARE_DIAS_ATTRIBUTE_SERVICE_ENDPOINT: https://dias/ws/services/DIASMessageReceiverService
    depends_on:
      - zk
      - redis
      - dias

  cte-user-service:
    hostname: cte-user-service
    image: docker.363-283.io/chimera/user-service:1.0.1-SNAPSHOT
    environment:
      ELASTICSEARCH_HOST: es
      ZK_HOST: zk
      JAVAX_PERSISTENCE_JDBC_URL: jdbc:postgresql://postgres:5432/chimera_test
      ZK_ANNOUNCEPOINT_AAC: /cte/service/aac/1.1
      ZOOKEEPER_URL: zk:2181
      GOV_IC_CTE_SERVER_CONFIG_ZK_ZOOKEEPERCONNECTION: zk:2181
    ports:
      - "7472:8443"
    depends_on:
      - zk
      - aac
      - postgres


  odrive:
    image: "deciphernow/odrive:latest"
    environment:
        - OD_AAC_CA=/go/src/decipher.com/object-drive-server/defaultcerts/client-aac/trust/client.trust.pem
        - OD_AAC_CERT=/go/src/decipher.com/object-drive-server/defaultcerts/client-aac/id/client.cert.pem
        - OD_AAC_HOST=aac                         # has default
        - OD_AAC_KEY=/go/src/decipher.com/object-drive-server/defaultcerts/client-aac/id/client.key.pem
        - OD_AAC_CN=twl-server-generic2
        - OD_AAC_INSECURE_SKIP_VERIFY=false
        - OD_PEER_CN=twl-server-generic2
        - OD_PEER_INSECURE_SKIP_VERIFY=false
        - OD_AWS_ACCESS_KEY_ID=$OD_AWS_ACCESS_KEY_ID
        - OD_AWS_ENDPOINT                    # has default
        - OD_AWS_REGION=us-east-1             # has default
        - OD_AWS_S3_BUCKET
        - OD_AWS_SECRET_ACCESS_KEY=$OD_AWS_SECRET_ACCESS_KEY
        - OD_AWS_SECRET_KEY=$OD_AWS_SECRET_ACCESS_KEY
        - OD_CACHE_EVICTAGE                   # has default
        - OD_CACHE_HIGHWATERMARK              # has default
        - OD_CACHE_LOWWATERMARK               # has default
        - OD_CACHE_ROOT
        - OD_CACHE_WALKSLEEP
        - OD_CACHE_PARTITION=finder
        - OD_DB_CA=/go/src/decipher.com/object-drive-server/defaultcerts/client-mysql/trust
        - OD_DB_CERT=/go/src/decipher.com/object-drive-server/defaultcerts/client-mysql/id/client-cert.pem
        - OD_DB_CONN_PARAMS=parseTime=true&collation=utf8_unicode_ci
        - OD_DB_HOST=metadatadb
        - OD_DB_KEY=/go/src/decipher.com/object-drive-server/defaultcerts/client-mysql/id/client-key.pem
        - OD_DB_MAXIDLECONNS
        - OD_DB_MAXOPENCONNS
        - OD_DB_PASSWORD=dbPassword
        - OD_DB_PORT=3306
        - OD_DB_SCHEMA=metadatadb
        - OD_DB_USERNAME=dbuser
        - OD_ENCRYPT_MASTERKEY
        - OD_EVENT_KAFKA_ADDRS=kafka:9092    # we need to scale this up, right?
        - OD_EVENT_ZK_ADDRS=zk:2181
        - OD_SERVER_CA=/go/src/decipher.com/object-drive-server/defaultcerts/server/trust.pem
        - OD_SERVER_CERT=/go/src/decipher.com/object-drive-server/defaultcerts/server/server.cert.pem
        - OD_SERVER_KEY=/go/src/decipher.com/object-drive-server/defaultcerts/server/server.key.pem
        - OD_SERVER_PORT=4430
        - OD_ZK_ANNOUNCE=/cte/service/object-drive/1.0
        - OD_ZK_AAC=/cte/service/aac/1.1/thrift
        - OD_ZK_TIMEOUT
        - OD_ZK_URL
        - OD_STANDALONE=false
    ports:
        - 4430:4430
        - 4480:4480
    depends_on:
        - metadatadb
        - aac
        - zk
        - dias
        - kafka

  metadatadb:
    image: "deciphernow/metadatadb:latest"
    mem_limit: 1024m
    cpuset: "0"
    environment:
      - MYSQL_CONTAINER_NAME=metadatadb
      - MYSQL_USER=dbuser
      - MYSQL_DATABASE=metadatadb
      - MYSQL_ROOT_PASSWORD=dbRootPassword
      - MYSQL_PASSWORD=dbPassword
      - OD_ENCRYPT_MASTERKEY
    ports:
      - 3306:3306
    command: "./docker-entrypoint.sh mysqld_safe"

  odrive-indexer:
    image: docker.363-283.io/bedrock/object-drive-indexer-service:1.0.0-SNAPSHOT
    environment:
      ODRIVE_TEMPLATES: "true"
      ODRIVE_FIELDS: "true"
      DEBUG: "false"
    depends_on:
      - es
      - kafka
      - zk

  dias:
    image: deciphernow/dias:latest    
    ports:
      - "8443:443"

  zk:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  redis:
    image: docker.363-283.io/docker/backend:redis-3.2.2
    depends_on:
      - zk

  es:
    hostname: es
    image:  docker.363-283.io/docker/backend:elasticsearch-1.7.2 # removed -FINDER for blank ES
    environment:
      - AAC_ZOOKEEPER_ANNOUNCEMENT_POINT=/cte/service/aac/1.1
    ports:
      - "9200:9200"
    depends_on:
      - zk
      - aac

  postgres:
    image: docker.363-283.io/docker/backend:postgres-9.4
    depends_on:
      - zk

  kafka:
    hostname: kafka
    image: wurstmeister/kafka:0.8.2.2
    environment:
      KAFKA_ADVERTISED_HOST: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_BROKER_ID: "9092"                # needed for v0.8.2.2, autogenerated in later versions
      KAFKA_ZOOKEEPER_CONNECT: zk
      KAFKA_CREATE_TOPICS: odrive-event:1:1  # topic:replication-factor:partitions
    ports:
      - "22181:2181"
      - "29092:9092"
      - "9092:9092"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock

  proxier:
    image: nginx
    environment:
       - AAC_SERVICE_HOST=aac
       - AAC_SERVICE_PORT=8443
       - FINDER_HOST=finder
       - FINDER_PORT=8443
       - CTE_APPS_SERVICE_HOST=apps
       - CTE_APPS_SERVICE_PORT=8443
       - CTE_USER_SERVICE_HOST=cte-user-service
       - CTE_USER_SERVICE_PORT=8443
       - ODRIVE_SERVICE_HOST=odrive
       - ODRIVE_SERVICE_PORT=4430
    volumes:
       - ./proxier:/tmp/docker
    ports:
       - "47080:80"
       - "8080:443"
    depends_on:
       - aac
       - finder
       - cte-user-service
       - odrive
  #    # The envsubst command will swap out anything in the input file that begins with $ with a corresponding env
  #    # variable, or if one can't be found, an empty string. Since nginx conf files also make use of $-prefixed
  #    # variables, we will pass in the specific variables we want envsubst to replace (this is called the "shell
  #    # format" argument). Also note that we need to escape our $-prefixed variables, docker-compose style, to
  #    # prevent docker-compose from trying to replace the variables (i.e., $VAR becomes $$VAR).
  #    # end of command: < /tmp/docker/odrive.nginx.conf.tpl > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'
    command: /bin/bash -c "env && envsubst '$$ODRIVE_SERVICE_HOST $$ODRIVE_SERVICE_PORT $$FINDER_EXTERNAL_IP $$FINDER_HOST $$FINDER_PORT $$AAC_SERVICE_HOST $$AAC_SERVICE_PORT $$CTE_APPS_SERVICE_HOST $$CTE_APPS_SERVICE_PORT $$CTE_USER_SERVICE_HOST $$CTE_USER_SERVICE_PORT' < /tmp/docker/odrive.nginx.conf.tpl > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

