#!/bin/bash

EC2=centos@52.23.153.111
rm -rf $GOPATH/src/bitbucket.di2e.net/dime/object-drive-server/cmd/metadataconnector/cache
rsync -azP $GOPATH/src/ $EC2:gocode/src
rsync -azP $OD_ROOT/ $EC2:javacode
