#!/bin/bash

TARFILE=ui-2017-09-26.tar
cd $GOPATH/src/bitbucket.di2e.net/dime/object-drive-server/docker
rm ui-*.tar
rm ui.tar
aws s3 cp s3://decipherers/$TARFILE $TARFILE
(
  mkdir ui
  cd ui
  tar xvf ../$TARFILE
  cp ../proxier/drive/settings.json opt/apps/drive/json/settings.json
  cp ../proxier/drive/chm_drive.json opt/apps/drive/json/chm_drive.json
  cp ../proxier/drive/piwik.js opt/apps/drive/json/piwik.js
  cp ../proxier/drive/piwik.php opt/apps/drive/json/piwik.php
  tar cvf ../ui.tar *
)
docker cp ui.tar docker_proxier_1:ui.tar
docker exec docker_proxier_1 tar xvf /ui.tar
docker exec docker_proxier_1 chown -R nginx:nginx /opt/apps
