#!/bin/bash

cd $GOPATH/src/decipher.com/object-drive-server/docker
wget https://s3.amazonaws.com/decipherers/rpms/object-drive/drive-ui/drive-1.0-1.0.4-6094-20170502-63a0b3eafb5f25a94d2caf94cb243f9d9b52cc0f.x86_64.rpm
#wget https://s3.amazonaws.com/decipherers/rpms/object-drive/drive-ui/drive-1.0-1.0.4-5152-20170417-876aa8bba300d6669cf1747e5537365b8dbfb8e5.x86_64.rpm
therpmat=`ls *.rpm`
therpm=$(basename $therpmat)
docker cp $therpmat docker_gatekeeper_1:$therpm
docker exec docker_gatekeeper_1 rpm -e drive
docker exec docker_gatekeeper_1 rpm -e drive-1.0
docker exec docker_gatekeeper_1 rpm -i $therpm
docker exec docker_gatekeeper_1 service nginx restart

open https://dockervm:8080/apps/drive/index.html
