#!/bin/bash

TARFILE=ui-2017-09-26.tar
cd $GOPATH/src/decipher.com/object-drive-server/docker
rm ui-*.tar
rm ui.tar
wget https://s3.amazonaws.com/decipherers/$TARFILE
(
  mkdir ui
  cd ui
  tar xvf ../$TARFILE
)
docker cp $TARFILE docker_proxier_1:ui.tar
docker exec docker_proxier_1 tar xvf /ui.tar
docker exec docker_proxier_1 chown -R nginx:nginx /opt/apps
rm -rf ui
rm ui-*.tar
