#!/bin/bash

#Generate a new cert

cnName=dockervm

rm server.p12
rm key.pem
rm cert.pem
rm server.jks

#Generate pem
openssl genrsa -out server.key.pem 2048 
openssl req -x509 -new -nodes -key server.key.pem -days 720 -out server.cert.pem -subj "/C=US/O=U.S. Government/OU=Decipher/CN=${cnName}" -nodes

#Make it pkcs12
openssl pkcs12 -export -in server.cert.pem -inkey server.key.pem -out server.p12 -name default -password pass:password

#Convert to jks
keytool -importkeystore \
	-deststorepass password \
	-destkeypass password \
	-destkeystore server.jks \
	-srckeystore server.p12 \
	-srcstoretype PKCS12 \
	-srcstorepass password \
	-alias default

keytool -list \
	-keystore server.jks \
	-storepass password \
	-storetype jks

cp server.cert.pem ../clients/client.trust.pem
cp server.jks $OD_ROOT/cte-security-service/aac-client-test/src/main/java/resources/server.jks
