#!/bin/bash
#
# Init file for redis
#
# Originally written by Jason Priebe <jpriebe@cbcnewmedia.com>
#
# chkconfig: - 80 12
# description: A persistent key-value database with network interface
# processname: redis-server
# config: /etc/redis.conf
# pidfile: /var/run/redis/redis

source /etc/init.d/functions

export REDIS_HOME=where
export REDIS_PROJ=who
export REDIS_PORT=port
export REDIS_PASSWORD=password

pidfile=/var/run/redis_${REDIS_PROJ}/redis.pid
RETVAL=0
prog="redis-server"

start() {
  echo -n $"Starting $prog: "
  daemon --user ${REDIS_PROJ}_redis --pidfile $pidfile /usr/sbin/$prog ${REDIS_HOME}/redis.conf
  RETVAL=$?
  echo
  [ $RETVAL -eq 0 ] && touch /var/lock/subsys/redis_${REDIS_PROJ}
  return $RETVAL
}

stop() {
    PID=`cat $pidfile 2>/dev/null`
    if [ -n "$PID" ]; then
        echo "Shutdown may take a while; redis needs to save the entire database";
        echo -n $"Shutting down $prog: "
  	if [ "${REDIS_PASSWORD}" = "" ]; then
          /usr/bin/redis-cli -p ${REDIS_PORT} shutdown
 	else
          /usr/bin/redis-cli -p ${REDIS_PORT} -a ${REDIS_PASSWORD} shutdown
	fi
        if checkpid $PID 2>&1; then
            echo_failure
            RETVAL=1
        else
            rm -f ${REDIS_HOME}/db/temp*rdb
            rm -f /var/lock/subsys/redis_${REDIS_PROJ}
            echo_success
            RETVAL=0
        fi
    else
        echo -n $"$prog is not running"
        echo_failure
        RETVAL=1
    fi

    echo
    return $RETVAL
}

restart() {
  stop
  start
}

condrestart() {
    [-e /var/lock/subsys/redis_${REDIS_PROJ}] && restart || :
}

case "$1" in
  start)
  start
  ;;
  stop)
  stop
  ;;
  status)
  status -p $pidfile $prog
  RETVAL=$?
  ;;
  restart)
  restart
  ;;
  condrestart|try-restart)
  condrestart
  ;;
   *)
  echo $"Usage: $0 {start|stop|status|restart|condrestart}"
  RETVAL=1
esac

exit $RETVAL


