#!/bin/bash

echo ""
echo "Self Extracting Installer"
echo ""

export TMPDIR=`mktemp -d /tmp/selfextract.XXXXX`

ARCHIVE=`awk '/^__ARCHIVE_BELOW__/ {print NR + 1; exit 0; }' $0`

tail -n+$ARCHIVE $0 | tar xz -C $TMPDIR

if [ -f "$1" ];
then
	cp "$1" $TMPDIR/
fi

CDIR=`pwd`
cd $TMPDIR
./installer "$1"

cd $CDIR
rm -rf $TMPDIR

exit 0

__ARCHIVE_BELOW__
