#!/bin/bash

# Entry script for AAC docker service

# TODO: we should ensure that we su down
# TODO: mount secrets properly

cat /etc/hosts | grep -v `hostname` > ./modifiedhosts
cp ./modifiedhosts /etc/hosts

# The default command to pass to the tanuki wrapper. The `console` command
# dumps output to stdout. Sending output to stdout is required to keep a 
# docker container "alive", so we choose this as the default.
#
START_COMMAND=console

# Optionally pass a different command to tanuki. Specifically, run `entry start`
# if you want control of the shell while AAC server is running and you're inside
# the Docker container.
#
if [ ! -z $1 ]; then
  START_COMMAND=$1
fi

cd /root
(
APP=cte-aac-service-server-1.0.0
/usr/sbin/redis-server /etc/redis.conf 2>&1 &
cd /opt/cte/aac-data-and-scripts/scripts
./loadRefDataIntoRedis.sh
touch /opt/cte/$APP/logs/application.log
chown cte:cte /opt/cte/$APP/logs/application.log
tail -f /opt/cte/$APP/logs/application.log &
/etc/init.d/$APP $START_COMMAND
)
#read FARK
