#!/bin/bash
mkdir -p bundle/certs
cp ../defaultcerts/clients/*.p12 bundle/certs
tar cf customer.tar bundle/
THEDATE=$(date +%Y%m%d)
aws s3 cp customer.tar s3://odrive-builds/customer/object-drive-quickstart.${THEDATE}.x86_64.tar --acl public-read

