#!/bin/bash

export OD_AAC_CA=
export OD_AAC_CERT=
export OD_AAC_HOST=
export OD_AAC_KEY=
export OD_AAC_PORT=
export OD_AWS_ACCESS_KEY_ID=
export OD_AWS_REGION=
export OD_AWS_S3_BUCKET=
export OD_AWS_S3_FETCH_MB=
export OD_AWS_SECRET_ACCESS_KEY=
export OD_CACHE_EVICTAGE=
export OD_CACHE_HIGHWATERMARK=
export OD_CACHE_LOWWATERMARK=
export OD_CACHE_PARTITION=
export OD_CACHE_ROOT=
export OD_CACHE_WALKSLEEP=
export OD_DB_CA=
export OD_DB_CERT=
export OD_DB_CONN_PARAMS=
export OD_DB_HOST=
export OD_DB_KEY=
export OD_DB_MAXIDLECONNS=
export OD_DB_MAXOPENCONNS=
export OD_DB_PASSWORD=
export OD_DB_PORT=
export OD_DB_SCHEMA=
export OD_DB_USERNAME=
export OD_DOCKERVM_OVERRIDE=
export OD_DOCKERVM_PORT=
export OD_ENCRYPT_MASTERKEY=
export OD_SERVER_CA=
export OD_SERVER_CERT=
export OD_SERVER_KEY=
export OD_SERVER_PORT=
export OD_STANDALONE=
export OD_ZK_AAC=
export OD_ZK_BASEPATH=
export OD_ZK_MYIP=
export OD_ZK_MYPORT=
export OD_ZK_ROOT=
export OD_ZK_TIMEOUT=
export OD_ZK_URL=


