delimiter //

# This stored procedure can be used to generate test data
# It is not part of the base schema and is primarily intended for development load testing
# The arguments for the procedure are as follows
# 1) max_object_type - An integer denoting how many object types will be
#                      generated taking the prefix 'Test Type ' followed by the
#                      number being added.  The value should be 1  or greater.
# 2) max_object - An integer denoting how many objects should be generated or
#                      updating that takes the base name 'Object #' followed by
#                      the number being added. It may additionally be prefixed
#                      and suffixed with arguments 5 (prefix) and 6 (suffix)
# 3) overwrite - An integer that should be 0 or 1, where 0 indicates that the
#                      objects will not be updated if they already exist, and
#                      1 indicates they will
# 4) random_parent - An integer that should be 0 or 1, where 1 indicates that
#                      objects being generated or updated will be assigned a
#                      parentId equal to a randomly selected object
# 5) prefix - A varchar(20) that allows for optional prefix to the object name
#                      to differentiate sets of generated objects
# 6) suffix - A varchar(20) that allows for optional suffix to the object name
#                      to differentiate sets of generated objects
# To load this script
#	source spTestData.sql
# To call the procedure generating 20 types, and 1000 objects with overwrite and
# random parent assignment
#	CALL sp_TestData(20,1000,1,1,'','');
# This will generate objects named 'Object #1', 'Object #2',  .. 'Object #1000'
# Using multiple instances connected to mysql, parallel calls may be performed as follows
#	-- First one generating 100,000 objects named 'A Object #'
#	CALL sp_TestData(20,100000,1,1,'A ','');
#	-- Second one generating 100,000 objects named 'B Object #'
#	CALL sp_TestData(20,100000,1,1,'B ','');
#	-- Third one generating or updating 100,000 objects named 'C Object #'
#	CALL sp_TestData(20,100000,1,1,'C ','');
#	-- Fourth one generating or updating 100,000 objects named 'C Object #'
#	CALL sp_TestData(20,100000,1,1,'C ','');
#	-- Fifth one that can generating 100,000 objects named 'C Object #', but wont update set overwrite is set to false denoted by 4th argument
#	CALL sp_TestData(20,100000,1,0,'C ','');
# As these instances all run, objects generated by the first sets prefixed by A
# and B will not overwrite each other, while the last 3 for set C are working
# with the same set of objects.

DROP PROCEDURE IF EXISTS sp_TestData
//
SELECT 'Creating procedure' as Action
//
CREATE PROCEDURE sp_TestData(
	IN max_object_type int,
	IN max_object int,
/*	IN overwrite tinyint(1),
	IN random_parent tinyint(1),
*/
    IN assignedParentId varchar(32),
	IN prefix varchar(20),
	IN suffix varchar(20)
)
BEGIN
	DECLARE player1 varchar(255) default 'cn=test tester01,ou=people,ou=dae,ou=chimera,o=u.s. government,c=us';
	DECLARE player2 varchar(255) default 'cn=test tester10,ou=people,ou=dae,ou=chimera,o=u.s. government,c=us';
	DECLARE cur_object_type int default 0;
	DECLARE new_type_name varchar(60) default '';
	DECLARE new_type_id binary(16) default '';
	DECLARE new_type_id_hex varchar(32) default '';
	DECLARE cur_object int default 0;
	DECLARE new_object_name varchar(60) default '';
	DECLARE new_object_id binary(16) default '';
	DECLARE count_user int default 0;
	DECLARE count_type int default 0;
	DECLARE count_object int default 0;
	DECLARE createdBy varchar(255) default '';
	DECLARE random_parent_number int default 0;
	DECLARE parent_id binary(16) default '';
	DECLARE change_token varchar(60) default '';
	DECLARE object_type_ids_hex varchar(2000) default '';
	DECLARE parent_id_hex varchar(32) default '';
	DECLARE parent_ids_hex varchar(5000) default '';
	DECLARE parent_ids_hex_ml int default 0;
    DECLARE new_object_acm varchar(2000) default '';
    DECLARE acm1 varchar(2000) default '{"version":"2.1.0","classif":"U","owner_prod":[],"atom_energy":[],"sar_id":[],"sci_ctrls":[],"disponly_to":[""],"dissem_ctrls":[],"non_ic":[],"rel_to":[],"fgi_open":[],"fgi_protect":[],"portion":"U","banner":"UNCLASSIFIED","dissem_countries":["USA"],"accms":[],"macs":[],"oc_attribs":[{"orgs":[],"missions":[],"regions":[]}],"f_clearance":["u"],"f_sci_ctrls":[],"f_accms":[],"f_oc_org":[],"f_regions":[],"f_missions":[],"f_share":[],"f_atom_energy":[],"f_macs":[],"disp_only":""}';
    DECLARE acm2 varchar(2000) default '{"version":"2.1.0","classif":"TS","owner_prod":[],"atom_energy":[],"sar_id":[],"sci_ctrls":["si","tk"],"disponly_to":[""],"dissem_ctrls":[""],"non_ic":[],"rel_to":[],"fgi_open":[],"fgi_protect":[],"portion":"TS//SI/TK","banner":"TOP SECRET//SI/TK","dissem_countries":["USA"],"accms":[],"macs":[],"oc_attribs":[{"orgs":[],"missions":[],"regions":[]}],"f_clearance":["ts"],"f_sci_ctrls":["si","tk"],"f_accms":[],"f_oc_org":[],"f_regions":[],"f_missions":[],"f_share":[],"f_atom_energy":[],"f_macs":[],"disp_only":""}';
    DECLARE acmkeyid_dissem_countries binary(16);
    DECLARE acmkeyid_f_accms binary(16);
    DECLARE acmkeyid_f_atom_energy binary(16);    
    DECLARE acmkeyid_f_clearance binary(16);
    DECLARE acmkeyid_f_macs binary(16);
    DECLARE acmkeyid_f_missions binary(16);
    DECLARE acmkeyid_f_oc_org binary(16);
    DECLARE acmkeyid_f_regions binary(16);
    DECLARE acmkeyid_f_sci_ctrls binary(16);
    DECLARE acmvalueid_si binary(16);
    DECLARE acmvalueid_tk binary(16);
    DECLARE acmvalueid_ts binary(16);
    DECLARE acmvalueid_u binary(16);
    DECLARE acmvalueid_USA binary(16);
    DECLARE acm1id binary(16);
    DECLARE acm2id binary(16);
    DECLARE acmpartid binary(16);
    DECLARE otherUser varchar(255) default '';

    /*
	IF random_parent > 0 THEN
		SET parent_ids_hex_ml = 5000-33;
		IF max_object * 33 < parent_ids_hex_ml THEN
			SET parent_ids_hex_ml = max_object * 33;
		END IF;
	END IF;
    */

	# Create player1 if not exist
	SELECT count(*) FROM user where distinguishedName = player1 INTO count_user;
	IF count_user = 0 THEN
		INSERT user SET distinguishedName = player1, createdBy = player1;
	END IF;
	# Create player2 if not exist
	SELECT count(*) FROM user where distinguishedName = player2 INTO count_user;
	IF count_user = 0 THEN
		INSERT user SET distinguishedName = player2, createdBy = player1;
	END IF;
    # Create ACM keys
    SELECT count(*) FROM acmkey where name = 'dissem_countries' and isdeleted = 0 INTO count_user;
    IF count_user = 0 THEN
        INSERT acmkey SET createdBy = player1, name = 'dissem_countries';
    END IF;
    SELECT id from acmkey where name = 'dissem_countries' and isdeleted = 0 INTO acmkeyid_dissem_countries;
    SELECT count(*) FROM acmkey where name = 'f_accms' and isdeleted = 0 INTO count_user;
    IF count_user = 0 THEN
        INSERT acmkey SET createdBy = player1, name = 'f_accms';
    END IF;
    SELECT id from acmkey where name = 'f_accms' and isdeleted = 0 INTO acmkeyid_f_accms;
    SELECT count(*) FROM acmkey where name = 'f_atom_energy' and isdeleted = 0 INTO count_user;
    IF count_user = 0 THEN
        INSERT acmkey SET createdBy = player1, name = 'f_atom_energy';
    END IF;
    SELECT id from acmkey where name = 'f_atom_energy' and isdeleted = 0 INTO acmkeyid_f_atom_energy;
    SELECT count(*) FROM acmkey where name = 'f_clearance' and isdeleted = 0 INTO count_user;
    IF count_user = 0 THEN
        INSERT acmkey SET createdBy = player1, name = 'f_clearance';
    END IF;
    SELECT id from acmkey where name = 'f_clearance' and isdeleted = 0 INTO acmkeyid_f_clearance;
    SELECT count(*) FROM acmkey where name = 'f_macs' and isdeleted = 0 INTO count_user;
    IF count_user = 0 THEN
        INSERT acmkey SET createdBy = player1, name = 'f_macs';
    END IF;
    SELECT id from acmkey where name = 'f_macs' and isdeleted = 0 INTO acmkeyid_f_macs;
    SELECT count(*) FROM acmkey where name = 'f_missions' and isdeleted = 0 INTO count_user;
    IF count_user = 0 THEN
        INSERT acmkey SET createdBy = player1, name = 'f_missions';
    END IF;
    SELECT id from acmkey where name = 'f_missions' and isdeleted = 0 INTO acmkeyid_f_missions;
    SELECT count(*) FROM acmkey where name = 'f_oc_org' and isdeleted = 0 INTO count_user;
    IF count_user = 0 THEN
        INSERT acmkey SET createdBy = player1, name = 'f_oc_org';
    END IF;
    SELECT id from acmkey where name = 'f_oc_org' and isdeleted = 0 INTO acmkeyid_f_oc_org;
    SELECT count(*) FROM acmkey where name = 'f_regions' and isdeleted = 0 INTO count_user;
    IF count_user = 0 THEN
        INSERT acmkey SET createdBy = player1, name = 'f_regions';
    END IF;
    SELECT id from acmkey where name = 'f_regions' and isdeleted = 0 INTO acmkeyid_f_regions;
    SELECT count(*) FROM acmkey where name = 'f_sci_ctrls' and isdeleted = 0 INTO count_user;
    IF count_user = 0 THEN
        INSERT acmkey SET createdBy = player1, name = 'f_sci_ctrls';
    END IF;
    SELECT id from acmkey where name = 'f_sci_ctrls' and isdeleted = 0 INTO acmkeyid_f_sci_ctrls;
    # Create ACM Values
    SELECT count(*) from acmvalue where name = 'si' and isdeleted = 0 INTO count_user;
    IF count_user = 0 THEN
        INSERT acmvalue SET createdBy = player1, name = 'si';
    END IF;
    SELECT id from acmvalue where name = 'si' and isdeleted = 0 INTO acmvalueid_si;
    SELECT count(*) from acmvalue where name = 'tk' and isdeleted = 0 INTO count_user;
    IF count_user = 0 THEN
        INSERT acmvalue SET createdBy = player1, name = 'tk';
    END IF;
    SELECT id from acmvalue where name = 'tk' and isdeleted = 0 INTO acmvalueid_tk;
    SELECT count(*) from acmvalue where name = 'ts' and isdeleted = 0 INTO count_user;
    IF count_user = 0 THEN
        INSERT acmvalue SET createdBy = player1, name = 'ts';
    END IF;
    SELECT id from acmvalue where name = 'ts' and isdeleted = 0 INTO acmvalueid_ts;
    SELECT count(*) from acmvalue where name = 'u' and isdeleted = 0 INTO count_user;
    IF count_user = 0 THEN
        INSERT acmvalue SET createdBy = player1, name = 'u';
    END IF;
    SELECT id from acmvalue where name = 'u' and isdeleted = 0 INTO acmvalueid_u;
    SELECT count(*) from acmvalue where name = 'USA' and isdeleted = 0 INTO count_user;
    IF count_user = 0 THEN
        INSERT acmvalue SET createdBy = player1, name = 'USA';
    END IF;
    SELECT id from acmvalue where name = 'USA' and isdeleted = 0 INTO acmvalueid_USA;
    SELECT count(*) from acm where name = 'dissem_countries=USA;f_clearance=u' and isdeleted = 0 INTO count_user;
    IF count_user = 0 THEN
        INSERT acm SET createdBy = player1, name = 'dissem_countries=USA;f_clearance=u';
        SELECT id from acm where name = 'dissem_countries=USA;f_clearance=u' and isdeleted = 0 INTO acm1id;
        INSERT acmpart SET createdBy = player1, acmid = acm1id, acmkeyid = acmkeyid_dissem_countries, acmvalueid = acmvalueid_USA;
        INSERT acmpart SET createdBy = player1, acmid = acm1id, acmkeyid = acmkeyid_f_clearance, acmvalueid = acmvalueid_u;
    END IF;
    SELECT id from acm where name = 'dissem_countries=USA;f_clearance=u' and isdeleted = 0 INTO acm1id;
    SELECT count(*) from acm where name = 'dissem_countries=USA;f_clearance=ts;f_sci_ctrls=si,tk' and isdeleted = 0 INTO count_user;
    IF count_user = 0 THEN
        INSERT acm SET createdBy = player1, name = 'dissem_countries=USA;f_clearance=ts;f_sci_ctrls=si,tk';
        SELECT id from acm where name = 'dissem_countries=USA;f_clearance=ts;f_sci_ctrls=si,tk' and isdeleted = 0 INTO acm2id;
        INSERT acmpart SET createdBy = player1, acmid = acm2id, acmkeyid = acmkeyid_dissem_countries, acmvalueid = acmvalueid_USA;
        INSERT acmpart SET createdBy = player1, acmid = acm2id, acmkeyid = acmkeyid_f_clearance, acmvalueid = acmvalueid_ts;
        INSERT acmpart SET createdBy = player1, acmid = acm2id, acmkeyid = acmkeyid_f_sci_ctrls, acmvalueid = acmvalueid_si;
        INSERT acmpart SET createdBy = player1, acmid = acm2id, acmkeyid = acmkeyid_f_sci_ctrls, acmvalueid = acmvalueid_tk;
    END IF;
    SELECT id from acm where name = 'dissem_countries=USA;f_clearance=ts;f_sci_ctrls=si,tk' and isdeleted = 0 INTO acm2id;

    IF LENGTH(assignedParentId) > 0 THEN
        SET parent_id := unhex(assignedParentId);
    ELSE
        SET parent_id := null;
    END IF;

	WHILE (cur_object < max_object) DO

		# Increment object counter
		SET cur_object := cur_object + 1;

		# Increment type counter
		SET cur_object_type := cur_object_type + 1;
		IF cur_object_type > max_object_type THEN
			SET cur_object_type := 1;
		END IF;

		# Type name
		SET new_type_name = concat('Test Type ', cur_object_type);
		# Make type if not exits
		IF cur_object_type = cur_object THEN
			SET new_type_id_hex := '';
			SELECT hex(id) FROM object_type WHERE name = new_type_name AND isDeleted = 0 INTO new_type_id_hex;
			IF new_type_id_hex IS NULL OR new_type_id_hex = '' THEN
				INSERT object_type SET createdBy = player1, name = new_type_name;
				SELECT hex(id) FROM object_type WHERE name = new_type_name AND isDeleted = 0 INTO new_type_id_hex;
			END IF;
			SET object_type_ids_hex := concat(object_type_ids_hex, ',', new_type_id_hex);
		END IF;

		# Get Type ID
		# Direct Position using cache
		SET new_type_id := unhex(substring(object_type_ids_hex, (2 + ((cur_object_type-1) * 33)), 32));
		# Find in DB
		# SELECT id FROM object_type WHERE name = new_type_name AND isDeleted = 0 INTO new_type_id;


		# Object name
		SET new_object_name = concat(prefix, 'Object #', cur_object, suffix);
        
        # Object ACM
        IF ((cur_object mod 2) > 0) THEN
            SET new_object_acm = acm1;
        ELSE
            SET new_object_acm = acm2;
        END IF;

		# See if an object of this name exists
		#SELECT count(*) FROM object WHERE name = new_object_name AND isDeleted = 0 INTO count_object;
		# Make if not exists or overwrite flag
		#IF count_object < 1 OR overwrite > 0 THEN

            /*
			# Random record number
			SET parent_id := NULL;
			IF random_parent <> 0 THEN
				## Only 99 percent will be attached to a parent.
				#IF cast(rand() * 100 as int) > 1 THEN
				IF cur_object > 50 THEN 
					# See if a cache of random parentIds is built yet
					IF length(parent_ids_hex) < parent_ids_hex_ml THEN
						SET random_parent_number := cast(rand() * cur_object as int);
						# SELECT cast(rand() * cur_object as int) INTO random_parent_number;
						# Note that this is kind of costly as it has to recalculate on each iteration...
						SELECT max(id) FROM (SELECT id FROM object limit random_parent_number) t1 INTO parent_id;
						# Add this parent to the cache
						SET parent_id_hex := hex(parent_id);
						SET parent_ids_hex := concat(parent_ids_hex, ',', parent_id_hex);
					ELSE
						# Choose a random parent number
						SET random_parent_number := cast(rand() * 30 as int);
						# Retrieve a parent by position from the cache
						SET parent_id_hex := substring(parent_ids_hex, (2 + (random_parent_number * 33)), 32);
					END IF;
					IF length(parent_id_hex) < 32 THEN
						# force choose
						SET random_parent_number := cast(rand() * cur_object as int);
						SELECT max(id) FROM (SELECT id FROM object limit random_parent_number) t1 INTO parent_id;
					END IF;
					SET parent_id := unhex(parent_id_hex);
				END IF;
			END IF;
            */
            


			# Determine user to be createdBy or modifiedBy
			SET createdBy := player1;
            SET otherUser := player2;
			IF ((cur_object mod 2) > 0) THEN
				SET createdBy := player2;
                SET otherUser := player1;
			END IF;

			# Insert or Update
			#IF count_object < 1 THEN
				# Does not exist yet...
				INSERT object SET createdBy = createdBy, name = new_object_name, rawacm = new_object_acm, typeId = new_type_id, parentId = parent_id;
                SELECT id FROM object WHERE name = new_object_name AND isDeleted = 0 LIMIT 1 INTO new_object_id;
                # Associate related acmkey and acmvalue
                IF ((cur_object mod 2) > 0) THEN
                    INSERT INTO objectacm SET createdBy = createdBy, objectId = new_object_id, acmid = acm1id;
                    # dissem_countries = USA, f_clearance = u
                    INSERT INTO object_acm SET createdBy = createdBy, objectId = new_object_id, acmkeyid = acmkeyid_dissem_countries, acmvalueid = acmvalueid_USA;
                    INSERT INTO object_acm SET createdBy = createdBy, objectId = new_object_id, acmkeyid = acmkeyid_f_clearance, acmvalueid = acmvalueid_u;
                ELSE
                    INSERT INTO objectacm SET createdBy = createdBy, objectId = new_object_id, acmid = acm2id;
                    # dissem_countries = USA, f_clearance = ts, f_sci_ctrls = si, tk
                    INSERT INTO object_acm SET createdBy = createdBy, objectId = new_object_id, acmkeyid = acmkeyid_dissem_countries, acmvalueid = acmvalueid_USA;
                    INSERT INTO object_acm SET createdBy = createdBy, objectId = new_object_id, acmkeyid = acmkeyid_f_clearance, acmvalueid = acmvalueid_ts;
                    INSERT INTO object_acm SET createdBy = createdBy, objectId = new_object_id, acmkeyid = acmkeyid_f_sci_ctrls, acmvalueid = acmvalueid_si;
                    INSERT INTO object_acm SET createdBy = createdBy, objectId = new_object_id, acmkeyid = acmkeyid_f_sci_ctrls, acmvalueid = acmvalueid_tk;
                END IF;                
                # Create permission records for access (grant full crud to creator, and explicit share read to other)
                INSERT INTO object_permission SET createdBy = createdBy, objectId = new_object_id, grantee = createdBy, allowCreate = 1, allowRead = 1, allowUpdate = 1, allowDelete = 1, allowShare = 1, explicitShare = 0;
                INSERT INTO object_permission SET createdBy = createdBy, objectId = new_object_id, grantee = otherUser, allowCreate = 0, allowRead = 1, allowUpdate = 0, allowDelete = 0, allowShare = 0, explicitShare = 1;
			#ELSE
			#	# Already present, lets update the name
			#	# Need to get change token and id first
			#	SELECT id, changeToken FROM object WHERE name = new_object_name AND isDeleted = 0 INTO new_object_id, change_token;
			#	UPDATE object SET modifiedBy = createdBy, typeId = new_type_id, parentId = parent_id, changeToken = change_token WHERE id = new_object_id;
			#END IF;
		#END IF;

	END WHILE;
END
//
delimiter ;
