source triggers.acm.create.sql
source triggers.acmkey.create.sql
source triggers.acmpart.create.sql
source triggers.acmvalue.create.sql
source triggers.dbstate.create.sql
source triggers.field_changes.create.sql
source triggers.object.create.sql
source triggers.objectacm.create.sql
source triggers.object_acm.create.sql
source triggers.object_permission.create.sql
source triggers.object_property.create.sql
source triggers.object_tag.create.sql
source triggers.object_type.create.sql
source triggers.object_type_property.create.sql
source triggers.property.create.sql
source triggers.relationship.create.sql
source triggers.user.create.sql
source triggers.user_object_favorite.create.sql
source triggers.user_object_subscription.create.sql
