#!/bin/bash

staticroot=$GOPATH/src/decipher.com/oduploader/cmd/metadataconnector/libs/server/static/templates

aglio --theme-variables streak -i home.md -o $staticroot/root.html
cp home.html $staticroot/root.html

