#!/bin/bash

echo supply a port number as a parameter

# Make the binary in our GOPATH
#(cd ../..; scripts/cross-compile.sh)

## Put cryptotest and the certs on the machine
where=centos@54.236.228.140
thebin=odrive-linux-64bit.tgz
scp $GOPATH/src/decipher.com/oduploader/release/$thebin $where:/home/centos/$thebin
scp defaultcerts/server/server.* $where:/home/centos/
ssh $where tar xvf $thebin
ssh -L$1:0.0.0.0:$1 $where AWS_REGION=$AWS_REGION masterkey=otterpaws ./cryptotest -tcpPort $1 -partition partition.$USER.$1 -serverTrustFile server.trust.pem -serverCertFile server.cert.pem -serverKeyFile server.key.pem
