#!/bin/bash

mkdir generated 2>&1 > /dev/null
openssl genrsa -out generated/server.key.pem 2048 && \
openssl req -x509 -new -nodes -key generated/server.key.pem -days 720 -out generated/server.cert.pem && \
openssl x509 -in generated/server.cert.pem -text
