#!/bin/bash

theuser=$1

openssl genrsa -out $theuser.key.pem 2048 && \
openssl req -new -key $theuser.key.pem -out $theuser.csr && \
openssl x509 -req -in $theuser.csr -CA cert.pem -CAkey key.pem -CAcreateserial -out $theuser.cert.pem && \
openssl x509 -in $theuser.cert.pem -text
chmod 400 $theuser.key.pem
openssl pkcs12 -export -in $theuser.cert.pem -inkey $theuser.key.pem -out $theuser.p12 -name $theuser

